### ISSUE TITLE
A question about this project

### ISSUE THREAD

**Issue by qaq54600** [ptoupas/amd-open-hardware-23#2]
Thank you for sharing! The project looks excellent, but I encountered some issues during deployment.

I want to generate .bit and .hwh files on my own board, but it seems that there are no Vivado project files in the project that make it impossible to proceed with subsequent work. If possible, can I refer the Vivado project?
Wishing you success in your work!

**Comment by ptoupas** [comment]
We really appreciate your feedback and interest in our project. Unfortunately, at this point, the Vivado project files are not available for sharing; however, the generated bitstream is already provided for your convenience.

However, we recognize the value of having access to the Vivado project for greater customization freedom. We'd like to let you know that we are currently working on an open-source version of the backend based on High-Level Synthesis (HLS). This will allow you to have more hands-on experience with the project's hardware generation part.

In the meantime, we invite you to look at our open-source HLS backend, which may provide you with some better insight into the tool's hardware generation.
You can have a look at [fpgaconvnet-hls](https://github.com/AlexMontgomerie/fpgaconvnet-hls) and [fpgaconvnet-tutorial](https://github.com/AlexMontgomerie/fpgaconvnet-tutorial)
